// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api;
using api.Src.ConsultationSpace.ConduiteSection.Entities;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526102451_IntroduceCustomlAnomalyCatalog")]
    partial class IntroduceCustomlAnomalyCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.CalendarSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndHour")
                        .HasColumnType("integer");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId")
                        .IsUnique();

                    b.ToTable("CalendarSettings");
                });

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EndTime")
                        .HasColumnType("text");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "Date");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.Rdv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPersonnel")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Motifs")
                        .HasColumnType("text[]");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonnelDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PersonnelDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("CabinetIdentityId", "Date");

                    b.ToTable("Rdvs");
                });

            modelBuilder.Entity("api.Src.AiChat.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("AiChatSessionId", "SortOrder");

                    b.ToTable("AiChatMessages");
                });

            modelBuilder.Entity("api.Src.AiChat.Entities.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("CabinetIdentityId", "UpdatedAt");

                    b.ToTable("AiChatSessions");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.CabinetIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeCnam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FlaggedForDeletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlaggedForDeletion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecondSecretaryActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordResetToken");

                    b.HasIndex("RefreshToken");

                    b.ToTable("CabinetIdentities");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("GoogleMapsLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstnameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Landline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastnameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SelfCheckinEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("SelfCheckinKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SelfCheckinTimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.DoctorPersonalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoDailyNewsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CylinderScale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DailyNews")
                        .HasColumnType("text");

                    b.Property<string>("DailyNewsAr")
                        .HasColumnType("text");

                    b.Property<string>("DailyNewsEn")
                        .HasColumnType("text");

                    b.Property<string>("DailyNewsFr")
                        .HasColumnType("text");

                    b.Property<string>("DistanceVisualScale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ShowCodeCnam")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFirstName")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFirstNameArabic")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFooter")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFooterCabinetAddress")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFooterEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFooterLandline")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFooterMobile")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLastName")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLastNameArabic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseSuperAdminDailyNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("WaitingRoomMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("DoctorPersonalizations");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Secretary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecretaryIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId");

                    b.ToTable("Secretaries");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConduiteConsigneCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId");

                    b.HasIndex("CabinetIdentityId", "LabelNormalized")
                        .IsUnique();

                    b.ToTable("ConduiteConsigneCatalogItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConduiteOrdonnanceTypeCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Consigne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InformationAdditionnel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<List<ConduiteOrdonnanceTypeDrugCatalogItem>>("ListDrugs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId");

                    b.HasIndex("CabinetIdentityId", "LabelNormalized")
                        .IsUnique();

                    b.HasIndex("CabinetIdentityId", "TypeKey")
                        .IsUnique();

                    b.ToTable("ConduiteOrdonnanceTypeCatalogItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConsultationConduiteAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, JsonElement>>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("ConsultationId", "ActionKey")
                        .IsUnique();

                    b.HasIndex("ConsultationId", "SortOrder");

                    b.ToTable("ConsultationConduiteActions");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConsultationLettreConfrereAiJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectionPrompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Formulepolitesse")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LetterName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Medecin")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Dictionary<string, JsonElement>>("ResultPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("CabinetIdentityId", "Status");

                    b.HasIndex("ConsultationId", "CreatedAt");

                    b.ToTable("ConsultationLettreConfrereAiJobs");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.DocumentsSection.Entities.ConsultationExplorationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Forfait")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Precaution")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("TypeLabels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("ConsultationId", "CreatedAt");

                    b.ToTable("ConsultationExplorationDocuments");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConduiteAdditionalInformation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTimerPaused")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "ConsultationDate");

                    b.HasIndex("PatientId", "ConsultationDate")
                        .IsUnique();

                    b.HasIndex("PatientId", "CabinetIdentityId", "ConsultationDate");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.Entities.ConsultationMotif", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ValueNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId", "ValueNormalized");

                    b.ToTable("ConsultationMotifs");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ExamSection.Entities.ConsultationExam", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, JsonElement>>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsultationId");

                    b.HasIndex("Payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.ToTable("ConsultationExams");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ExamSection.Entities.ExamFindingCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SectionNormalized")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "SectionNormalized");

                    b.HasIndex("CabinetIdentityId", "SectionNormalized", "LabelNormalized")
                        .IsUnique();

                    b.ToTable("ExamFindingCatalogItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Diagnostics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HistoireMaladie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsultationId");

                    b.ToTable("Interrogatoires");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.InterrogatoireAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, JsonElement>>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("ConsultationId", "TemplateKey");

                    b.HasIndex("ConsultationId", "Section", "SortOrder");

                    b.ToTable("InterrogatoireAnomalies");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.InterrogatoireAnomalyCatalogCustom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "Section");

                    b.HasIndex("CabinetIdentityId", "Section", "LabelNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_InterrogatoireAnomalyCatalogCustoms_CabinetIdentityId_Sect~1");

                    b.ToTable("InterrogatoireAnomalyCatalogCustoms");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.InterrogatoireAnomalyCatalogHidden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "Section");

                    b.HasIndex("CabinetIdentityId", "Section", "LabelNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_InterrogatoireAnomalyCatalogHiddens_CabinetIdentityId_Sect~1");

                    b.ToTable("InterrogatoireAnomalyCatalogHiddens");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.OngoingTreatmentMedicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Medicine")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Posology")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TherapeuticClass")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("OngoingTreatmentMedicines");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.TherapeuticClassCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "LabelNormalized")
                        .IsUnique();

                    b.ToTable("TherapeuticClassCatalogItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.TreatmentCatalogRelationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CategoryNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Medicine")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("MedicineNormalized")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("TherapeuticClass")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TherapeuticClassNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "CategoryNormalized", "MedicineNormalized");

                    b.HasIndex("CabinetIdentityId", "TherapeuticClassNormalized", "CategoryNormalized");

                    b.HasIndex("CabinetIdentityId", "TherapeuticClassNormalized", "CategoryNormalized", "MedicineNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_TreatmentCatalogRelationItems_CabinetIdentityId_Therapeuti~1");

                    b.ToTable("TreatmentCatalogRelationItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.TreatmentCategoryCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "LabelNormalized")
                        .IsUnique();

                    b.ToTable("TreatmentCategoryCatalogItems");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.TreatmentMedicineCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("LabelNormalized")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId", "LabelNormalized")
                        .IsUnique();

                    b.ToTable("TreatmentMedicineCatalogItems");
                });

            modelBuilder.Entity("api.Src.Messaging.Entities.InternalMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.PrimitiveCollection<string[]>("SeenBy")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("CabinetIdentityId", "RoomId", "CreatedAt");

                    b.ToTable("InternalMessages");
                });

            modelBuilder.Entity("api.Src.PatientSpace.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("APCI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DossierNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilialStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceEstablishment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("api.Src.Subscription.Entities.ActiveSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasBeenNotifiedOfExpiration")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CabinetIdentityId")
                        .IsUnique();

                    b.ToTable("ActiveSubscriptions");
                });

            modelBuilder.Entity("api.Src.Subscription.Entities.FileToDelete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FilesToDelete");
                });

            modelBuilder.Entity("api.Src.Suggestions.Entities.DoctorSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LastReplyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SeenByAdmins")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SeenByAdminsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeenByAdmins");

                    b.HasIndex("Status");

                    b.HasIndex("CabinetIdentityId", "UpdatedAt");

                    b.ToTable("DoctorSuggestions");
                });

            modelBuilder.Entity("api.Src.Suggestions.Entities.DoctorSuggestionReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorSuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReadByDoctor")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadByDoctorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResponderDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponderFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ResponderLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ResponderRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReadByDoctor");

                    b.HasIndex("ResponderDoctorId");

                    b.HasIndex("DoctorSuggestionId", "CreatedAt");

                    b.ToTable("DoctorSuggestionReplies");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(420)
                        .HasColumnType("character varying(420)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TechAssistanceMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TechAssistanceMessageId");

                    b.ToTable("TechAssistanceAttachments");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReadByRequester")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadByRequesterAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderCabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SenderFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SenderLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TechAssistanceTicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReadByRequester");

                    b.HasIndex("SenderRole");

                    b.HasIndex("TechAssistanceTicketId", "CreatedAt");

                    b.ToTable("TechAssistanceMessages");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinetIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LastAdminMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastDoctorMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SeenByAdmins")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SeenByAdminsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime?>("TechLeadNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("SeenByAdmins");

                    b.HasIndex("Status");

                    b.HasIndex("CabinetIdentityId", "UpdatedAt");

                    b.ToTable("TechAssistanceTickets");
                });

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.CalendarSettings", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.Leave", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.AgendaSpace.Entities.Rdv", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Src.PatientSpace.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CabinetIdentity");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("api.Src.AiChat.Entities.AiChatMessage", b =>
                {
                    b.HasOne("api.Src.AiChat.Entities.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("AiChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("api.Src.AiChat.Entities.AiChatSession", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Clinic", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Doctor", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithOne("Doctor")
                        .HasForeignKey("api.Src.Auth.Entities.Doctor", "CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.DoctorPersonalization", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.Doctor", "Doctor")
                        .WithOne("Personalization")
                        .HasForeignKey("api.Src.Auth.Entities.DoctorPersonalization", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Secretary", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany("Secretaries")
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConsultationConduiteAction", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithMany("ConduiteActions")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ConduiteSection.Entities.ConsultationLettreConfrereAiJob", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.DocumentsSection.Entities.ConsultationExplorationDocument", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithMany("ExplorationDocuments")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.Entities.Consultation", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany("Consultations")
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Src.PatientSpace.Entities.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.Entities.ConsultationMotif", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithMany("Motifs")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.ExamSection.Entities.ConsultationExam", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithOne("Exam")
                        .HasForeignKey("api.Src.ConsultationSpace.ExamSection.Entities.ConsultationExam", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.Entities.Consultation", "Consultation")
                        .WithOne("Interrogatoire")
                        .HasForeignKey("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.InterrogatoireAnomaly", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", "Interrogatoire")
                        .WithMany("Anomalies")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interrogatoire");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.OngoingTreatmentMedicine", b =>
                {
                    b.HasOne("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", "Interrogatoire")
                        .WithMany("OngoingTreatments")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interrogatoire");
                });

            modelBuilder.Entity("api.Src.Messaging.Entities.InternalMessage", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.PatientSpace.Entities.Patient", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany("Patients")
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.Subscription.Entities.ActiveSubscription", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithOne("ActiveSubscriptions")
                        .HasForeignKey("api.Src.Subscription.Entities.ActiveSubscription", "CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.Suggestions.Entities.DoctorSuggestion", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.Suggestions.Entities.DoctorSuggestionReply", b =>
                {
                    b.HasOne("api.Src.Suggestions.Entities.DoctorSuggestion", "Suggestion")
                        .WithMany("Replies")
                        .HasForeignKey("DoctorSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Src.Auth.Entities.Doctor", "ResponderDoctor")
                        .WithMany()
                        .HasForeignKey("ResponderDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResponderDoctor");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceAttachment", b =>
                {
                    b.HasOne("api.Src.TechAssistance.Entities.TechAssistanceMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("TechAssistanceMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceMessage", b =>
                {
                    b.HasOne("api.Src.TechAssistance.Entities.TechAssistanceTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TechAssistanceTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceTicket", b =>
                {
                    b.HasOne("api.Src.Auth.Entities.CabinetIdentity", "CabinetIdentity")
                        .WithMany()
                        .HasForeignKey("CabinetIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinetIdentity");
                });

            modelBuilder.Entity("api.Src.AiChat.Entities.AiChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.CabinetIdentity", b =>
                {
                    b.Navigation("ActiveSubscriptions");

                    b.Navigation("Consultations");

                    b.Navigation("Doctor");

                    b.Navigation("Patients");

                    b.Navigation("Secretaries");
                });

            modelBuilder.Entity("api.Src.Auth.Entities.Doctor", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("Personalization");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.Entities.Consultation", b =>
                {
                    b.Navigation("ConduiteActions");

                    b.Navigation("Exam");

                    b.Navigation("ExplorationDocuments");

                    b.Navigation("Interrogatoire")
                        .IsRequired();

                    b.Navigation("Motifs");
                });

            modelBuilder.Entity("api.Src.ConsultationSpace.InterrogationSection.Entities.Interrogatoire", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("OngoingTreatments");
                });

            modelBuilder.Entity("api.Src.PatientSpace.Entities.Patient", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("api.Src.Suggestions.Entities.DoctorSuggestion", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("api.Src.TechAssistance.Entities.TechAssistanceTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
