export const PREDEFINED_MOTIFS: string[] = [
  'Acné',
  'Rosacée',
  'Eczéma',
  'Dermatite atopique',
  'Dermatite de contact',
  'Psoriasis',
  'Urticaire',
  'Prurit',
  'Éruption cutanée',
  'Lésion suspecte',
  'Grain de beauté suspect',
  'Naevus à surveiller',
  'Mélanome suspecté',
  'Carcinome basocellulaire',
  'Carcinome épidermoïde',
  'Kératose actinique',
  'Kératose séborrhéique',
  'Verrues',
  'Condylomes',
  'Molluscum contagiosum',
  'Herpès',
  'Zona',
  'Varicelle',
  'Mycose cutanée',
  'Candidose',
  'Pityriasis versicolor',
  'Teigne',
  'Onychomycose',
  'Folliculite',
  'Furoncle',
  'Abcès cutané',
  'Cellulite',
  'Impétigo',
  'Érysipèle',
  'Vitiligo',
  'Chute de cheveux',
  'Alopécie',
  'Pelade',
  'Alopécie androgénétique',
  'Dermite séborrhéique',
  'Pellicules',
  'Hyperhidrose',
  'Transpiration excessive',
  'Bromhidrose',
  'Angiome',
  'Taches pigmentaires',
  'Mélasma',
  'Chloasma',
  'Cicatrice',
  'Cicatrice chéloïde',
  'Brûlure',
  'Coup de soleil',
  'Photosensibilité',
  'Allergie cutanée',
  'Œdème de Quincke',
  'Piqûre insecte',
  'Morsure',
  'Ulcère cutané',
  'Ulcère variqueux',
  'Escarres',
  'Plaie chronique',
  'Kyste sébacé',
  'Lipome',
  'Xanthélasma',
  'Hirsutisme',
  'Hypertrichose',
  'Couperose',
  'Télangiectasies',
  'Varices',
  'Insuffisance veineuse',
  'Prurit anal',
  'Prurit vulvaire',
  'Lichen plan',
  'Lichen scléreux',
  'Pemphigus',
  'Pemphigoïde bulleuse',
  'Lupus érythémateux',
  'Sclérodermie',
  'Morphée',
  'Purpura',
  'Pétéchies',
  'Érythème noueux',
  'Sarcoïdose cutanée',
  'Dermatomyosite',
  'Vascularite cutanée',
  'Pytiriasis rosé',
  'Intertrigo',
  'Perlèche',
  'Chéilite',
  'Aphtes',
  'Leucoplasie',
  'Gale',
  'Pédiculose',
  'Poux',
  'Consultation préventive',
  'Dépistage cancer cutané',
  'Contrôle naevi',
  'Suivi dermatologique',
  'Renouvellement ordonnance',
  'Certificat médical',
  'Chirurgie dermatologique',
  'Retrait lésion',
  'Cryothérapie',
  'Laser dermatologique',
  'Peeling',
  'Injection botox',
  'Injection acide hyaluronique',
  'Traitement rides',
  'Traitement cicatrices',
  'Épilation laser',
];
