export const PREDEFINED_MOTIFS: string[] = [
  'Fièvre',
  'Toux sèche',
  'Toux grasse',
  'Rhinorrhée',
  'Maux de gorge',
  'Dyspnée',
  'Douleur thoracique',
  'Palpitations',
  'Céphalée',
  'Vertiges',
  'Fatigue générale',
  'Asthénie',
  'Douleur abdominale',
  'Nausées',
  'Vomissements',
  'Diarrhée',
  'Constipation',
  'Brûlures épigastriques',
  'Reflux gastro-œsophagien',
  'Dysurie',
  'Pollakiurie',
  'Hématurie',
  'Infection urinaire suspectée',
  'Douleur lombaire',
  'Lombalgie',
  'Sciatalgie',
  'Douleur cervicale',
  'Douleur épaule',
  'Arthralgies',
  'Myalgies',
  'Entorse',
  'Traumatisme mineur',
  'Éruption cutanée',
  'Prurit',
  'Plaie simple',
  'Brûlure mineure',
  'Rhinite allergique',
  'Allergie saisonnière',
  'Sinusite suspectée',
  'Otalgie',
  'Otite suspectée',
  'Conjonctivite',
  'Bronchite suspectée',
  "Crise d'asthme",
  'Suivi HTA',
  'Suivi diabète',
  'Suivi hypothyroïdie',
  'Bilan de santé',
  'Renouvellement ordonnance',
  'Certificat médical',
  'Vaccination',
  'Insomnie',
  'Anxiété',
  'Humeur dépressive',
  'Sevrage tabagique',
  'Perte de poids',
  'Prise de poids',
  'Œdèmes des membres inférieurs',
  'Douleur pelvienne',
  'Troubles menstruels',
  'Aménorrhée',
  'Contraception',
  'Suivi grossesse',
  'Contrôle post-hospitalisation',
];
